#!/bin/bash

set -x
set -e

# This is intended to be run on Jenkins, where GIT_BRANCH is populated
result=$(echo "${GIT_BRANCH}" | grep --only-matching '[0-9]\+\.[0-9]\+\.[0-9]\+$')

echo -n ${result}
